import cv2
import numpy as np
import pandas as pd
from ultralytics import YOLO
import yt_dlp
import os
from pathlib import Path

def get_youtube_stream(url):
    try:
        ydl_opts = {'format': 'best[height<=720]', 'quiet': True, 'noplaylist': True}
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            return ydl.extract_info(url, download=False)['url']
    except Exception as e:
        print(f"YouTube Error: {e}")
        return None

def load_parking_spots(csv_path):
    """Loads parking spot coordinates from the CSV generated by the mapper."""
    if not os.path.exists(csv_path):
        print(f"❌ Error: Could not find {csv_path}")
        return {}
        
    df = pd.read_csv(csv_path)
    spots = {}
    
    for index, row in df.iterrows():
        # Reconstruct the 4-point polygon
        polygon = np.array([
            [row['Point1_X'], row['Point1_Y']],
            [row['Point2_X'], row['Point2_Y']],
            [row['Point3_X'], row['Point3_Y']],
            [row['Point4_X'], row['Point4_Y']]
        ], np.int32)
        spots[row['SpotID']] = polygon
        
    return spots

def run_parking_monitor(video_source, root_dir, csv_name):
    # 1. Load the mapped spots
    csv_path = os.path.join(root_dir, 'data', csv_name)
    spots = load_parking_spots(csv_path)
    if not spots:
        return

    # 2. Setup YOLO Model
    model_candidates = [
        os.path.join(root_dir, 'yolov8n.pt'),
        os.path.join(root_dir, 'yolov8s.pt'),
    ]
    model_path = next((path for path in model_candidates if os.path.exists(path)), None)
    if model_path is None:
        raise FileNotFoundError("Missing yolov8n.pt and yolov8s.pt in the project root.")
    model = YOLO(model_path)

    # 3. Setup Video Stream
    final_video_path = video_source
    if "youtube.com" in video_source or "youtu.be" in video_source:
        print("Extracting YouTube stream...")
        final_video_path = get_youtube_stream(video_source)
    elif not video_source.startswith(('http', 'https')):
        final_video_path = os.path.join(root_dir, video_source)

    cap = cv2.VideoCapture(final_video_path)
    if not cap.isOpened():
        print(f"❌ Error: Could not open video.")
        return

    print("\n===========================================")
    print(" 🚗 PARKING HELPER: LIVE MONITORING STARTED")
    print("===========================================")
    print(f"- Monitoring {len(spots)} spots loaded from {csv_name}.")
    print("- Press 'q' to quit.")

    cv2.namedWindow("Parking Monitor", cv2.WINDOW_NORMAL)

    while True:
        ret, frame = cap.read()
        if not ret: 
            # Loop the video if it ends
            cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
            continue

        # Create a dictionary to track the status of each spot this frame (Default: False / Empty)
        spot_status = {spot_id: False for spot_id in spots.keys()}

        # Run YOLO detection
        results = model.predict(frame, verbose=False, conf=0.25)
        
        # Check detected vehicles against parking spots
        for det in results[0].boxes.data:
            x1, y1, x2, y2, conf, cls = map(int, det[:6])
            
            # If the detection is a vehicle (car, motorcycle, bus, truck)
            if cls in [2, 3, 5, 7]: 
                # Calculate the center point of the bounding box
                cx = int((x1 + x2) / 2)
                cy = int((y1 + y2) / 2)
                
                # Check which spot this vehicle's center point falls inside
                for spot_id, polygon in spots.items():
                    if cv2.pointPolygonTest(polygon, (cx, cy), False) >= 0:
                        spot_status[spot_id] = True # Mark as occupied
                        break # Move to the next vehicle

        # --- DRAWING THE UI ---
        display_frame = frame.copy()
        occupied_count = 0

        for spot_id, polygon in spots.items():
            if spot_status[spot_id]:
                # Occupied = Red
                color = (0, 0, 255)
                thickness = 2
                occupied_count += 1
            else:
                # Empty = Green
                color = (0, 255, 0)
                thickness = 2

            # Draw the spot polygon
            cv2.polylines(display_frame, [polygon], isClosed=True, color=color, thickness=thickness)
            
            # Draw the Spot ID
            text_pos = (polygon[0][0], polygon[0][1] - 5)
            cv2.putText(display_frame, spot_id, text_pos, cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

        # Draw the main dashboard counter
        total_spots = len(spots)
        available_spots = total_spots - occupied_count
        
        # Dashboard Background
        cv2.rectangle(display_frame, (10, 10), (400, 90), (0, 0, 0), -1)
        
        # Status Text
        cv2.putText(display_frame, f"Parking Helper Monitor", (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 2)
        
        if available_spots > 0:
            status_color = (0, 255, 0)
            status_text = f"Available: {available_spots} / {total_spots}"
        else:
            status_color = (0, 0, 255)
            status_text = f"LOT FULL (0 / {total_spots})"
            
        cv2.putText(display_frame, status_text, (20, 75), cv2.FONT_HERSHEY_SIMPLEX, 0.8, status_color, 2)

        cv2.imshow("Parking Monitor", display_frame)
        
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()

def main():
    root_dir = Path(__file__).resolve().parents[1]
    
    print("=== Live Parking Monitor ===")
    video_input = input("1. Enter video file path or YouTube URL:\n> ").strip()
    if not video_input:
        return
        
    csv_input = input("\n2. Enter the CSV name to load (e.g., PL01.csv):\n> ").strip()
    if not csv_input.endswith('.csv'):
        csv_input += '.csv'
        
    run_parking_monitor(video_input, root_dir, csv_input)

if __name__ == '__main__':
    main()
